### ISSUE TITLE
Can't edit or save any maps.

### ISSUE THREAD

**Issue by ruderaliss** [XboxChaos/Downloader#1]
System.UnauthorizedAccessException: Access to the path 'C:\Users\Austin Huffman\AppData\Local\Temp\update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Assembly.Helpers.VariousFunctions.EmptyUpdaterLocations()
   at Assembly.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ruderaliss** [comment]
tried a windows 7 pc and a windows 10, same error. tried alot of things

**Comment by ThunderWaffle** [comment]
It look like to me you might have tried to run the program without extracting it from the ZIP file in comes packaged in.  Can you check on that and let me know if anything changes?

**Comment by adierking** [comment]
It doesn't seem to be an issue with running from the zip file since those files are always deleted from the temp directory:

https://github.com/XboxChaos/Assembly/blob/master/src/Assembly/Helpers/VariousFunctions.cs#L23

Somehow some sort of permissions mismatch is happening that causes the error. Not exactly sure what went wrong here, but we might want to catch any exceptions that come out of trying to delete those files since it's not at all critical.

**Comment by ThunderWaffle** [comment]
Oh I misread.  I didn't see that was a delete.  Made an assumption that it was trying to launch the updater instead.

**Comment by ThunderWaffle** [comment]
As for the issue, @ruderaliss I would think if you extracted the downloader to somewhere other than a temporary directory, it should run just fine (eg your documents/desktop).

I'll update this bug report with some labels.

**Comment by ruderaliss** [comment]
this happens when i try to save something everytime, i don't think that's the issue i will put the maps on my desktop and try it, it's on a flashdrive currently

**Comment by ruderaliss** [comment]
System.UnauthorizedAccessException: Access to the path 'E:\Content\maps\010_jungle.map' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode, FileAccess access)
   at Blamite.IO.FileStreamManager.OpenReadWrite()
   at Assembly.Metro.Controls.PageTemplates.Games.Components.MetaEditor.UpdateMeta(SaveType type, Boolean onlyUpdateChanged, Boolean showActionDialog)
   at Assembly.Metro.Controls.PageTemplates.Games.Components.MetaEditor.btnPluginSave_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ruderaliss** [comment]
i used to use this program alot a few years ago. worked fine till i got back into it 2 days ago

**Comment by ThunderWaffle** [comment]
That error looks like your map might be read only (it failed to write to the map when you clicked save in the editor but loaded it just fine).  Check the file properties for the map at "E:\Content\maps\010_jungle.map"

**Comment by ruderaliss** [comment]
thanks bro

**Comment by 0xdeafcafe** [comment]
Did that solve your issue @ruderaliss?

**Comment by ThunderWaffle** [comment]
@0xdeafcafe I assume it did.  I am going to leave this open though because there actually is something worth changing in the assembly code base.
