### ISSUE TITLE
Trying to install Assembly for the first time

### ISSUE THREAD

**Issue by O1C0A6C8** [XboxChaos/Downloader#2]
I keep getting this error message

Error: unable to communicate with the server! (ClientError, 4)

System.Net.WebException: The remote server returned an error: (522) Origin Connection Time-out.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XboxChaos.Net.ApiRequest.<SendAsync>d__0`1.MoveNext()

Any ideas on what to do?

**Comment by adierking** [comment]
Thank you for reporting this!

It looks like the updater is broken right now because I'm getting the same error. We'll work on fixing this and then we'll let you know when it's working again.

**Comment by O1C0A6C8** [comment]
Ok thank you, I thought it was something just on my end.

**Comment by 0xdeafcafe** [comment]
The MSDN subscription it was running on ran out. PM me @adierking
