### ISSUE TITLE
Direct Not Found Exception on install.

### ISSUE THREAD

**Issue by Vuthakral** [XboxChaos/Downloader#3]
`System.IO.DirectoryNotFoundException: Could not find a part of the path '<This is my system directory, removed for reasons>\Assembly\Formats\Engines.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at Downloader.ViewModels.ExtractViewModel.ExtractArchive(ZipArchive archive)
   at Downloader.ViewModels.ExtractViewModel.WorkerOnDoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)`

Assembly.exe and AssemblySettings.ason will appear in the folder, but nothing else downloads/extracts.

**Comment by adierking** [comment]
Thanks for reporting. Looking into it.

**Comment by adierking** [comment]
Should be fixed now, grab the new downloader from https://github.com/XboxChaos/Assembly/releases/tag/downloader
