### ISSUE TITLE
Error: Unable to extract the zip archive!

### ISSUE THREAD

**Issue by WayUltimateKoolDude921** [XboxChaos/Downloader#6]
"System.UnauthorizedAccessException: Access to the path 'C:\Program Files\HaloModding\Assembly\Assembly.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at Downloader.ViewModels.ExtractViewModel.ExtractArchive(ZipArchive archive)
   at Downloader.ViewModels.ExtractViewModel.WorkerOnDoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)"

That's the stuff I'm missing, think/ I'm assuming that's the case.

**Comment by Lord-Zedd** [comment]
Program Files might not be the best location for Assembly. Windows typically wants admin privileges for interacting with that directory so it isn't recommended.
